// Aqui puedes agregar los datos que necesites para tus pruebas
// al menos debe tener uno que se llame "data"

export const data = [
  {
    "id": "begonia",
    "categoryPlant":"ornamental",
    "name": "Begonia",
    "maintenanceNeeds": "Necesita riego regular y evitar la luz solar directa.",
    "scientificName": "Begonia",
    "applicationsPlant": "Jardinería decorativa, colecciones botánicas.",
    "climaticData": "Prefiere ambientes húmedos y sombreados.",
    "facts": {
      "waterAmount":1,
      "sunLight": 1,
      "careDifficulty":3,
    },
  },
  {
    "id": "aloevera",
    "categoryPlant":"medicinal",
    "name": "Aloe Vera",
    "maintenanceNeeds": "Riego escaso y exposición a pleno sol o sombra parcial.",
    "scientificName": "Aloe barbadensis miller",
    "applicationsPlant": "Productos medicinales y cosméticos, jardinería.",
    "climaticData": "Resistente a la sequía, prefiere climas cálidos.",
    "facts": {
      "waterAmount":2,
      "sunLight": 2,
      "careDifficulty":1,
    },
  },
  {
    "id": "menta",
    "categoryPlant":"aromatica",
    "name": "Menta",
    "maintenanceNeeds": "Controlar su crecimiento invasivo y proporcionar suficiente agua.",
    "scientificName": "Mentha",
    "applicationsPlant": "Cocina, bebidas, productos de higiene, remedios naturales.",
    "climaticData": "Prefiere suelos húmedos y lugares con sombra parcial.",
    "facts": {
      "waterAmount":2,
      "sunLight": 2,
      "careDifficulty":2,
    },
  },
  {
    "id": "manzanilla",
    "categoryPlant":"medicinal",
    "name": "Manzanilla",
    "maintenanceNeeds": "Necesita sol pleno y suelo bien drenado.",
    "scientificName": "Matricaria chamomilla",
    "applicationsPlant": "Infusiones, remedios naturales, cosmética.",
    "climaticData": "Prefiere climas templados y suelo bien drenado.",
    "facts": {
      "waterAmount":2,
      "sunLight": 2,
      "careDifficulty":3,
    },
  },
  {
    "id": "albahaca",
    "categoryPlant":"aromatica",
    "name": "Albahaca",
    "maintenanceNeeds": "Requiere sol pleno y riego regular, evitar exceso de humedad.",
    "scientificName": "Ocimum basilicum",
    "applicationsPlant": "Cocina, jardinería ornamental, aceites esenciales.",
    "climaticData": "Prefiere climas cálidos y suelo bien drenado.",
    "facts": {
      "waterAmount":3,
      "sunLight": 2,
      "careDifficulty":3,
    },
  },
  {
    "id": "azalea",
    "categoryPlant":"ornamental",
    "name": "Azalea",
    "maintenanceNeeds": "Requiere suelo ácido y poda después de la floración.",
    "scientificName": "Rhododendron",
    "applicationsPlant": "Jardinería ornamental, cultivo en macetas.",
    "climaticData": "Prefiere climas templados y suelo bien drenado.",
    "facts": {
      "waterAmount":2,
      "sunLight": 1,
      "careDifficulty":2,
    },
  },
  {
    "id": "roble",
    "categoryPlant":"arbol",
    "name": "Roble",
    "maintenanceNeeds": "Requiere espacio para crecer, poco mantenimiento una vez establecido.",
    "scientificName": "Quercus",
    "applicationsPlant": "Construcción, muebles, barriles para vino.",
    "climaticData": "Adaptable a diversos climas, prefiere suelos profundos.",
    "facts": {
      "waterAmount":2,
      "sunLight": 3,
      "careDifficulty":2,
    },
  },
  {
    "id": "ocotillo",
    "categoryPlant":"desertica",
    "name": "Ocotillo",
    "maintenanceNeeds": "Requiere poca agua y suelo bien drenado.",
    "scientificName": "Fouquieria splendens",
    "applicationsPlant": "Jardinería xerófila, ornamentación, cercas vivas.",
    "climaticData": "Adaptable a condiciones áridas, prefiere suelo bien drenado.",
    "facts": {
      "waterAmount":1,
      "sunLight": 3,
      "careDifficulty":2,
    },
  },
]